/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdvertisementBuyAd: typeof import('./src/components/advertisement/buyAd.vue')['default']
    AdvertisementComponentsAdCard: typeof import('./src/components/advertisement/components/adCard.vue')['default']
    AdvertisementMyAd: typeof import('./src/components/advertisement/myAd.vue')['default']
    AdvertisementSaleAd: typeof import('./src/components/advertisement/saleAd.vue')['default']
    BusinessApply: typeof import('./src/components/business/apply.vue')['default']
    BusinessApply2: typeof import('./src/components/business/apply2.vue')['default']
    BusinessApplyBusiness: typeof import('./src/components/business/applyBusiness.vue')['default']
    BusinessBusinessInfo: typeof import('./src/components/business/businessInfo.vue')['default']
    Empty: typeof import('./src/components/empty/index.vue')['default']
    HomeListCard: typeof import('./src/components/home/listCard/index.vue')['default']
    OrderBusinessOrderDisputedOrder: typeof import('./src/components/order/businessOrder/disputedOrder.vue')['default']
    OrderBusinessOrderOfflineOrder: typeof import('./src/components/order/businessOrder/offlineOrder.vue')['default']
    OrderBusinessOrderOnlineOrder: typeof import('./src/components/order/businessOrder/onlineOrder.vue')['default']
    OrderBusinessOrderOrderCard: typeof import('./src/components/order/businessOrder/orderCard.vue')['default']
    OrderBusinessOrderOrderDetail: typeof import('./src/components/order/businessOrder/orderDetail.vue')['default']
    OrderMyOrder: typeof import('./src/components/order/myOrder/index.vue')['default']
    OrderMyOrderComponentsDisputedOrder: typeof import('./src/components/order/myOrder/components/disputedOrder.vue')['default']
    OrderMyOrderComponentsOfflineOrder: typeof import('./src/components/order/myOrder/components/offlineOrder.vue')['default']
    OrderMyOrderComponentsOnlineOrder: typeof import('./src/components/order/myOrder/components/onlineOrder.vue')['default']
    OrderMyOrderComponentsOrderCard: typeof import('./src/components/order/myOrder/components/orderCard.vue')['default']
    OrderMyOrderComponentsOrderDetail: typeof import('./src/components/order/myOrder/components/orderDetail.vue')['default']
    OrderPlaceOrderBuy: typeof import('./src/components/order/placeOrder/buy.vue')['default']
    OrderPlaceOrderComponentsAppeal: typeof import('./src/components/order/placeOrder/components/appeal.vue')['default']
    OrderPlaceOrderComponentsAuthSuccess: typeof import('./src/components/order/placeOrder/components/authSuccess.vue')['default']
    OrderPlaceOrderComponentsBuySuccess: typeof import('./src/components/order/placeOrder/components/buySuccess.vue')['default']
    OrderPlaceOrderComponentsPaySuccess: typeof import('./src/components/order/placeOrder/components/paySuccess.vue')['default']
    OrderPlaceOrderComponentsUpload: typeof import('./src/components/order/placeOrder/components/upload.vue')['default']
    OrderPlaceOrderSale: typeof import('./src/components/order/placeOrder/sale.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/service/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}
